language: php

dist: xenial

notifications:
  email: false

php:
  - "7.1"

matrix:
  fast_finish: true

# TRAVIS_ERROR_LEVEL = E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_STRICT
env: TRAVIS_ERROR_LEVEL=22519 OX_BASE_PATH="$TRAVIS_BUILD_DIR/source/" OXID_ESHOP_CS_THRESHOLD=14

services: mysql

before_install:
  - echo 'Europe/Berlin' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - sudo apt-get update

before_script:
  # apache setup (http://docs.travis-ci.com/user/languages/php/#Apache-%2B-PHP)
  - sudo apt-get install apache2 libapache2-mod-fastcgi xfce4-session
  # enable php-fpm
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - if [[ $(phpenv version-name) = 7.* ]]; then cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf; fi;
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - phpenv config-rm xdebug.ini
  # configure apache virtual host
  - echo "$(curl -fsSL https://gist.githubusercontent.com/adriankirchner/197e3d13ccfb680f8942/raw/5b36cd3740cc05adb1c9d5c0568c851dd7700dcc/gistfile1.apacheconf)" | sudo tee /etc/apache2/sites-available/default > /dev/null
  - sudo sed -e "s|%TRAVIS_BUILD_DIR%|$(pwd)/source|g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

  # database setup
  - sudo sed -e 's|utf8_unicode_ci|latin1_general_ci|g; s|utf8|latin1|g' --in-place /etc/mysql/my.cnf
  - sudo service mysql restart

  - cp source/config.inc.php.dist source/config.inc.php
  - sh ./.travis.before_script.sh

  # set permissions to log directory
  - chmod -R 777 "${TRAVIS_BUILD_DIR}/source/log"

  # composer initiation
  - SHOP_PATH='source' SHOP_TESTS_PATH='tests' MODULES_PATH='' composer install

script:
  - xvfb-run --server-args="-screen 0, 1024x768x24" ${TRAVIS_BUILD_DIR}/start_selenium.sh
  - vendor/bin/runtests
